name: Check project
on:
  push:

jobs:
  check-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typescript

      - name: Build packages
        run: yarn lerna run prepare
