name: Test all templates
on:
  pull_request:
    branches:
      - main

jobs:
  test-all-templates:
    name: Test all templates
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [module, view]
        language: [java-objc, java-swift, kotlin-objc, kotlin-swift, cpp, js]
        example: [native]
        include:
          - type: module
            language: js
            example: expo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.13.x
          cache: yarn

      - name: Restore root level yarn cache
        id: root-yarn-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-root-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.root-yarn-cache.outputs.cache-hit != 'true'
        working-directory: ./packages/create-react-native-library
        run: |
          yarn install --frozen-lockfile

      - name: Build package
        working-directory: ./packages/create-react-native-library
        run: |
          yarn prepare

      - name: Create example app
        working-directory: ./packages/create-react-native-library/bin
        run: |
          ./create-react-native-library test --slug test --description test --author-name test --author-email test@test --author-url https:// --repo-url https:// --type ${{ matrix.type }} --languages ${{ matrix.language }} --example ${{ matrix.example }}

      - name: Restore dependencies of example app
        id: example-app-yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            packages/create-react-native-library/bin/test/node_modules
            packages/create-react-native-library/bin/test/example/node_modules
          key: ${{ runner.os }}-example-app-yarn-${{ matrix.type }}-${{ matrix.language }}-${{ matrix.example}}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies of example app
        if: steps.example-app-yarn-cache.outputs.cache-hit != 'true'
        working-directory: ./packages/create-react-native-library/bin/test
        run: |
          yarn install

      - name: Lint example app
        working-directory: ./packages/create-react-native-library/bin/test
        run: |
          yarn lint

      - name: Generate types of example app
        working-directory: ./packages/create-react-native-library/bin/test
        run: |
          yarn typescript

      - name: Run tests on example app
        working-directory: ./packages/create-react-native-library/bin/test
        run: |
          yarn test
